#![allow(dead_code)]

// PostgreSQL execution proof for the only legacy `timestamp without time
// zone` value used by the port.  Java/PgJDBC stores a wall clock in the JVM
// timezone; Rust must write the same wall clock and convert it back to an
// instant with the configured legacy timezone, independently of the database
// session timezone.

#[path = "../src/infra/postgres/legacy_timestamp.rs"]
mod legacy_timestamp;

#[cfg(test)]
mod database_contract_tests {
    use chrono::{DateTime, Utc};
    use sqlx::{PgPool, postgres::PgPoolOptions};

    use crate::legacy_timestamp::sLegacyJdbcTimezone;

    fn vValidateDisposableTimestampDatabase(
        sCurrentDatabase: &str,
        sExpectedDatabase: &str,
    ) -> anyhow::Result<()> {
        anyhow::ensure!(
            sCurrentDatabase == sExpectedDatabase,
            "connected database {sCurrentDatabase:?} does not match LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_EXPECT_DATABASE {sExpectedDatabase:?}"
        );

        let sLower = sCurrentDatabase.to_ascii_lowercase();
        let bProtectedToken = sLower
            .split(|cCharacter: char| !cCharacter.is_ascii_alphanumeric())
            .any(|sToken| matches!(sToken, "live" | "prod" | "production"));
        anyhow::ensure!(
            !matches!(sLower.as_str(), "lor" | "postgres")
                && !sLower.starts_with("template")
                && !bProtectedToken,
            "refusing to run the legacy timestamp contract against protected database {sCurrentDatabase:?}"
        );
        anyhow::ensure!(
            sLower.starts_with("lorsource_timestamp_test_"),
            "disposable timestamp database name must start with lorsource_timestamp_test_; got {sCurrentDatabase:?}"
        );
        Ok(())
    }

    async fn vExecute(oPool: &PgPool, sSql: &str) -> anyhow::Result<()> {
        // Dynamic statements contain only the UUID-hex schema generated by
        // this test. No fixture, environment, or request value enters them.
        sqlx::query(sqlx::AssertSqlSafe(sSql.to_owned()))
            .execute(oPool)
            .await?;
        Ok(())
    }

    async fn vProveTimestampRoundTrip(oPool: &PgPool) -> anyhow::Result<()> {
        sqlx::query(
            "CREATE TABLE comments(\
                 id integer PRIMARY KEY,\
                 edit_date timestamp without time zone NOT NULL\
             )",
        )
        .execute(oPool)
        .await?;

        let sLegacyTimezone = sLegacyJdbcTimezone(chrono_tz::Europe::Berlin);
        for (iId, sInstant) in [
            (1_i32, "2026-01-15 12:34:56+00"),
            (2_i32, "2026-07-15 12:34:56+00"),
        ] {
            sqlx::query(
                "INSERT INTO comments(id,edit_date) \
                 VALUES($1,$2::timestamptz AT TIME ZONE $3::text)",
            )
            .bind(iId)
            .bind(sInstant)
            .bind(sLegacyTimezone)
            .execute(oPool)
            .await?;
        }

        let vecRows = sqlx::query_as::<_, (i32, DateTime<Utc>)>(
            "SELECT id, edit_date AT TIME ZONE $1::text \
             FROM comments ORDER BY id",
        )
        .bind(sLegacyTimezone)
        .fetch_all(oPool)
        .await?;
        anyhow::ensure!(
            vecRows
                == vec![
                    (1, "2026-01-15T12:34:56Z".parse::<DateTime<Utc>>()?),
                    (2, "2026-07-15T12:34:56Z".parse::<DateTime<Utc>>()?),
                ],
            "legacy timestamp summer/winter round trip changed instants: {vecRows:?}"
        );

        let vecWallClocks = sqlx::query_as::<_, (i32, chrono::NaiveDateTime)>(
            "SELECT id, edit_date FROM comments ORDER BY id",
        )
        .fetch_all(oPool)
        .await?;
        anyhow::ensure!(
            vecWallClocks[0].1.to_string() == "2026-01-15 13:34:56"
                && vecWallClocks[1].1.to_string() == "2026-07-15 14:34:56",
            "legacy wall clocks did not use the configured DST-aware timezone: {vecWallClocks:?}"
        );

        let dtBefore: DateTime<Utc> = sqlx::query_scalar("SELECT CURRENT_TIMESTAMP")
            .fetch_one(oPool)
            .await?;
        sqlx::query(
            "INSERT INTO comments(id,edit_date) \
             VALUES(3,CURRENT_TIMESTAMP AT TIME ZONE $1::text)",
        )
        .bind(sLegacyTimezone)
        .execute(oPool)
        .await?;
        let dtWritten: DateTime<Utc> =
            sqlx::query_scalar("SELECT edit_date AT TIME ZONE $1::text FROM comments WHERE id=3")
                .bind(sLegacyTimezone)
                .fetch_one(oPool)
                .await?;
        let dtAfter: DateTime<Utc> = sqlx::query_scalar("SELECT CURRENT_TIMESTAMP")
            .fetch_one(oPool)
            .await?;
        anyhow::ensure!(
            dtWritten >= dtBefore && dtWritten <= dtAfter,
            "production CURRENT_TIMESTAMP expression did not round-trip: {dtBefore:?} <= {dtWritten:?} <= {dtAfter:?}"
        );
        Ok(())
    }

    #[test]
    fn timestamp_database_guard_rejects_live_and_mismatched_names() {
        vValidateDisposableTimestampDatabase(
            "lorsource_timestamp_test_20260816",
            "lorsource_timestamp_test_20260816",
        )
        .expect("matching disposable timestamp database");

        for (sCurrent, sExpected) in [
            ("lor", "lor"),
            ("postgres", "postgres"),
            ("template0", "template0"),
            ("template1", "template1"),
            ("live", "live"),
            (
                "lorsource_timestamp_test_live",
                "lorsource_timestamp_test_live",
            ),
            (
                "lorsource_timestamp_test_prod",
                "lorsource_timestamp_test_prod",
            ),
            (
                "lorsource_timestamp_test_one",
                "lorsource_timestamp_test_two",
            ),
            ("unrelated_test_database", "unrelated_test_database"),
        ] {
            assert!(
                vValidateDisposableTimestampDatabase(sCurrent, sExpected).is_err(),
                "unsafe database pair was accepted: {sCurrent:?}/{sExpected:?}"
            );
        }
    }

    #[test]
    fn production_comment_timestamp_sql_uses_the_explicit_legacy_timezone() {
        // Keep the executable PostgreSQL proof tied to the actual production
        // call sites. Otherwise this integration test could keep proving its
        // copied SQL while a route or repository silently regressed to the
        // connection TimeZone (or to a hard-coded UTC conversion).
        let sCommentRoute = include_str!("../src/routes/comments.rs");
        let sEditHandler = sCommentRoute
            .split(concat!("pub async fn ", "edit_comment("))
            .nth(1)
            .expect("production edit_comment handler")
            .split(concat!("pub async fn ", "delete_comment_form("))
            .next()
            .expect("end of production edit_comment handler");
        assert!(sEditHandler.contains("edit_date=(CURRENT_TIMESTAMP AT TIME ZONE $4::text)"));
        assert!(sEditHandler.contains("state.config.stLegacyJdbcTimezone(),"));
        assert!(!sEditHandler.contains(concat!("edit_date=", "now()")));

        for sRepositorySource in [
            include_str!("../src/infra/postgres/topic_repository.rs"),
            include_str!("../src/infra/postgres/comment_deletion_repository.rs"),
        ] {
            let sRepository = sRepositorySource
                .split("\n#[cfg(test)]")
                .next()
                .expect("production repository source before its tests");
            assert!(sRepository.contains("(c.edit_date AT TIME ZONE $1::text) AS opt_edit_date"));
            assert!(sRepository.contains("legacy_timestamp::sLegacyJdbcTimezone("));
            assert!(!sRepository.contains("AT TIME ZONE 'UTC'"));
        }
    }

    #[tokio::test]
    #[ignore = "requires a separately created lorsource_timestamp_test_* throwaway database"]
    async fn legacy_comment_edit_timestamp_round_trips_across_session_timezone() {
        assert_eq!(
            std::env::var("LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_CONFIRM").as_deref(),
            Ok("isolated-database"),
            "set LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_CONFIRM=isolated-database"
        );
        let sDatabaseUrl = std::env::var("LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_DATABASE_URL")
            .expect("set LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_DATABASE_URL");
        let sExpectedDatabase =
            std::env::var("LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_EXPECT_DATABASE")
                .expect("set LOR_LEGACY_TIMESTAMP_DB_INTEGRATION_EXPECT_DATABASE");

        let oAdminPool = PgPoolOptions::new()
            .max_connections(1)
            .connect(&sDatabaseUrl)
            .await
            .expect("disposable PostgreSQL database must be reachable");
        let sCurrentDatabase: String = sqlx::query_scalar("SELECT current_database()::text")
            .fetch_one(&oAdminPool)
            .await
            .expect("read current disposable database name");
        vValidateDisposableTimestampDatabase(&sCurrentDatabase, &sExpectedDatabase)
            .expect("timestamp test requires a named throwaway database, never the live database");

        let sSchema = format!("legacy_timestamp_{}", uuid::Uuid::new_v4().simple());
        vExecute(&oAdminPool, &format!("CREATE SCHEMA {sSchema}"))
            .await
            .expect("temporary UUID schema must be creatable");

        let stResult = async {
            let sConnectionSchema = sSchema.clone();
            let oPool = PgPoolOptions::new()
                .max_connections(2)
                .after_connect(move |oConnection, _stMetadata| {
                    let sConnectionSchema = sConnectionSchema.clone();
                    Box::pin(async move {
                        sqlx::query("SELECT set_config('search_path',$1,false)")
                            .bind(sConnectionSchema)
                            .execute(&mut *oConnection)
                            .await?;
                        // Deliberately differs from Europe/Berlin so the test
                        // catches accidental session-TimeZone conversion.
                        sqlx::query("SELECT set_config('TimeZone','Pacific/Honolulu',false)")
                            .execute(&mut *oConnection)
                            .await?;
                        Ok(())
                    })
                })
                .connect(&sDatabaseUrl)
                .await?;

            let stContractResult = async {
                let (sCurrentSchema, sSessionTimezone): (String, String) = sqlx::query_as(
                    "SELECT current_schema()::text, current_setting('TimeZone')::text",
                )
                .fetch_one(&oPool)
                .await?;
                anyhow::ensure!(sCurrentSchema == sSchema);
                anyhow::ensure!(sSessionTimezone == "Pacific/Honolulu");
                vProveTimestampRoundTrip(&oPool).await
            }
            .await;

            oPool.close().await;
            stContractResult
        }
        .await;

        let stDropResult = vExecute(&oAdminPool, &format!("DROP SCHEMA {sSchema} CASCADE")).await;
        oAdminPool.close().await;
        stDropResult.expect("temporary UUID schema cleanup must succeed");
        stResult.expect("legacy timestamp database contract");
    }
}
