#![allow(dead_code)]

// Isolated PostgreSQL proof for the case-sensitive identity contract.  The
// web routes have their own binder tests; this harness proves that repository
// lookups cannot combine private/reset/activation data from two legacy rows
// whose nicknames differ only by case.

mod error {
    #[derive(Debug, thiserror::Error)]
    pub enum AppError {
        #[error("database error: {0}")]
        Sqlx(#[from] sqlx::Error),
    }

    pub type Result<T> = std::result::Result<T, AppError>;
}

mod domain {
    pub mod email {
        pub mod address {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/domain/email/address.rs"
            ));
        }
    }

    pub mod user {
        pub mod identity {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/domain/user/identity.rs"
            ));
        }
    }
}

mod application {
    pub mod user {
        pub mod identity {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/application/user/identity.rs"
            ));
        }
    }
}

mod infra {
    pub mod postgres {
        pub mod user_identity_repository {
            include!(concat!(
                env!("CARGO_MANIFEST_DIR"),
                "/src/infra/postgres/user_identity_repository.rs"
            ));
        }
    }
}

#[cfg(test)]
mod database_contract_tests {
    use chrono::{TimeZone, Utc};
    use sqlx::{PgPool, postgres::PgPoolOptions};

    use crate::{
        application::user::identity::CUserIdentityService,
        domain::user::identity::TrUserIdentityRepository,
        infra::postgres::user_identity_repository::CUserIdentityPgRepository,
    };

    fn vValidateDisposableIdentityDatabase(
        sCurrentDatabase: &str,
        sExpectedDatabase: &str,
    ) -> anyhow::Result<()> {
        anyhow::ensure!(
            sCurrentDatabase == sExpectedDatabase,
            "connected database {sCurrentDatabase:?} does not match LOR_USER_IDENTITY_DB_INTEGRATION_EXPECT_DATABASE {sExpectedDatabase:?}"
        );

        let sLower = sCurrentDatabase.to_ascii_lowercase();
        let bProtectedToken = sLower
            .split(|cCharacter: char| !cCharacter.is_ascii_alphanumeric())
            .any(|sToken| matches!(sToken, "live" | "prod" | "production"));
        anyhow::ensure!(
            !matches!(sLower.as_str(), "lor" | "postgres")
                && !sLower.starts_with("template")
                && !bProtectedToken,
            "refusing to run the identity contract against protected database {sCurrentDatabase:?}"
        );
        anyhow::ensure!(
            sLower.starts_with("lorsource_identity_test_"),
            "disposable identity database name must start with lorsource_identity_test_; got {sCurrentDatabase:?}"
        );
        Ok(())
    }

    async fn vExecute(oPool: &PgPool, sSql: &str) -> anyhow::Result<()> {
        // Dynamic statements contain only the UUID-hex schema generated by
        // this test. No fixture, environment, or request value enters them.
        sqlx::query(sqlx::AssertSqlSafe(sSql.to_owned()))
            .execute(oPool)
            .await?;
        Ok(())
    }

    async fn vCreateIdentityFixture(oPool: &PgPool) -> anyhow::Result<()> {
        for sSql in [
            r#"CREATE FUNCTION normalize_email(email text)
               RETURNS text
               LANGUAGE plpgsql IMMUTABLE
               AS $function$
                 DECLARE
                   localpart text;
                   domainpart text;
                 BEGIN
                   SELECT regexp_replace(email, '@[^@]*$', '') INTO localpart;
                   SELECT regexp_replace(email, '.*@', '') INTO domainpart;
                   IF domainpart = 'gmail.com' THEN
                     SELECT regexp_replace(localpart, '[.]', '', 'g') INTO localpart;
                   END IF;
                   RETURN concat(localpart, '@', domainpart);
                 END;
               $function$"#,
            r#"CREATE TABLE users(
                   id integer PRIMARY KEY,
                   nick text NOT NULL UNIQUE,
                   email text,
                   regdate timestamptz,
                   activated boolean NOT NULL,
                   lostpwd timestamptz NOT NULL,
                   blocked boolean,
                   canmod boolean NOT NULL,
                   candel boolean NOT NULL,
                   passwd text,
                   score integer NOT NULL,
                   lastlogin timestamptz NOT NULL
               )"#,
            r#"CREATE TABLE user_settings(
                   id integer PRIMARY KEY REFERENCES users(id),
                   settings text NOT NULL
               )"#,
            r#"CREATE TABLE user_events(
                   userid integer NOT NULL REFERENCES users(id),
                   type text NOT NULL
               )"#,
            r#"INSERT INTO users(
                   id,nick,email,regdate,activated,lostpwd,blocked,canmod,candel,passwd,score,lastlogin
               ) VALUES
                   (10,'anonymous','lower@example.test',
                    '2024-01-02 03:04:05+00',false,
                    '2026-02-03 04:05:06+00',false,false,false,'lower-hash',200,
                    '2026-08-01 01:02:03+00'),
                   (20,'Anonymous','upper@example.test',
                    '2025-06-07 08:09:10+00',true,
                    '2026-07-08 09:10:11+00',true,false,true,'',300,
                    '2026-08-02 04:05:06+00'),
                   (30,'gmail-unblocked-older','u.ser.name@gmail.com',
                    '2025-01-01 00:00:00+00',true,
                    '2026-01-01 00:00:00+00',false,true,false,'gmail-older-hash',100,
                    '2026-08-03 00:00:00+00'),
                   (50,'gmail-blocked-newer','username@gmail.com',
                    '2025-01-02 00:00:00+00',true,
                    '2026-01-02 00:00:00+00',true,false,false,'gmail-blocked-hash',100,
                    '2026-08-04 00:00:00+00'),
                   (60,'gmail-unblocked-low-id','second.user@gmail.com',
                    '2025-01-03 00:00:00+00',true,
                    '2026-01-03 00:00:00+00',false,false,false,'gmail-low-hash',100,
                    '2026-08-05 00:00:00+00'),
                   (70,'gmail-unblocked-high-id','s.e.c.o.n.d.u.s.e.r@gmail.com',
                    '2025-01-04 00:00:00+00',true,
                    '2026-01-04 00:00:00+00',false,true,false,'gmail-high-hash',100,
                    '2026-08-06 00:00:00+00'),
                   (80,'blocked-null',NULL,
                    '2025-01-05 00:00:00+00',true,
                    '2026-08-07 00:00:00+00',true,false,false,'blocked-null-hash',100,
                    '2026-08-07 00:00:00+00'),
                   (90,'eligible-null',NULL,
                    '2025-01-06 00:00:00+00',true,
                    '2026-08-08 00:00:00+00',false,false,false,'eligible-null-hash',100,
                    '2026-08-08 00:00:00+00')"#,
            r#"INSERT INTO user_settings(id,settings) VALUES
                   (10,'lower-private-settings'),
                   (20,'upper-private-settings')"#,
            r#"INSERT INTO user_events(userid,type) VALUES
                   (10,'LowerPrivateReply'),
                   (20,'UpperPrivateReply')"#,
        ] {
            vExecute(oPool, sSql).await?;
        }
        Ok(())
    }

    async fn vProvePasswordResetRequestOrdering(oPool: &PgPool) -> anyhow::Result<()> {
        let cService = CUserIdentityService::new(CUserIdentityPgRepository::new(oPool.clone()));

        let stUnblocked = cService
            .optPasswordResetRequestIdentity("User.Name@GMAIL.COM")
            .await?
            .ok_or_else(|| anyhow::anyhow!("normalized Gmail identity was not resolved"))?;
        anyhow::ensure!(stUnblocked.iId == 30);
        anyhow::ensure!(stUnblocked.sNick == "gmail-unblocked-older");
        anyhow::ensure!(stUnblocked.sEmail == "u.ser.name@gmail.com");
        anyhow::ensure!(!stUnblocked.bBlocked);
        anyhow::ensure!(stUnblocked.bActivated);
        anyhow::ensure!(stUnblocked.bModerator);
        anyhow::ensure!(!stUnblocked.bAdministrator);
        anyhow::ensure!(!stUnblocked.bAnonymous);

        let stHighestId = cService
            .optPasswordResetRequestIdentity("seconduser@gmail.com")
            .await?
            .ok_or_else(|| anyhow::anyhow!("second normalized Gmail identity was not resolved"))?;
        anyhow::ensure!(stHighestId.iId == 70);
        anyhow::ensure!(stHighestId.sNick == "gmail-unblocked-high-id");
        anyhow::ensure!(stHighestId.sEmail == "s.e.c.o.n.d.u.s.e.r@gmail.com");
        anyhow::ensure!(!stHighestId.bBlocked);
        anyhow::ensure!(stHighestId.bActivated);
        anyhow::ensure!(stHighestId.bModerator);
        anyhow::ensure!(!stHighestId.bAdministrator);
        anyhow::ensure!(!stHighestId.bAnonymous);
        Ok(())
    }

    async fn vProveExactIdentityContract(oPool: &PgPool) -> anyhow::Result<()> {
        let cRepository = CUserIdentityPgRepository::new(oPool.clone());

        let stLower = cRepository
            .optExactIdentity("anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("lower-case identity was not resolved"))?;
        let stUpper = cRepository
            .optExactIdentity("Anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("upper-case identity was not resolved"))?;
        anyhow::ensure!((stLower.iId, stLower.sNick.as_str()) == (10, "anonymous"));
        anyhow::ensure!((stUpper.iId, stUpper.sNick.as_str()) == (20, "Anonymous"));
        anyhow::ensure!(cRepository.optExactIdentity("ANONYMOUS").await?.is_none());
        anyhow::ensure!(!cRepository.bExactNickExists("ANONYMOUS").await?);

        let stLowerActivation = cRepository
            .optActivationIdentity("anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("lower-case activation identity was not resolved"))?;
        anyhow::ensure!(stLowerActivation.iId == 10);
        anyhow::ensure!(stLowerActivation.sNick == "anonymous");
        anyhow::ensure!(stLowerActivation.optEmail.as_deref() == Some("lower@example.test"));
        anyhow::ensure!(
            stLowerActivation.optRegistrationDate
                == Some(Utc.with_ymd_and_hms(2024, 1, 2, 3, 4, 5).unwrap())
        );
        anyhow::ensure!(!stLowerActivation.bActivated);

        let stUpperActivation = cRepository
            .optActivationIdentity("Anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("upper-case activation identity was not resolved"))?;
        anyhow::ensure!(stUpperActivation.iId == 20);
        anyhow::ensure!(stUpperActivation.sNick == "Anonymous");
        anyhow::ensure!(stUpperActivation.optEmail.as_deref() == Some("upper@example.test"));
        anyhow::ensure!(
            stUpperActivation.optRegistrationDate
                == Some(Utc.with_ymd_and_hms(2025, 6, 7, 8, 9, 10).unwrap())
        );
        anyhow::ensure!(stUpperActivation.bActivated);
        anyhow::ensure!(
            cRepository
                .optActivationIdentity("ANONYMOUS")
                .await?
                .is_none()
        );

        let stLowerReset = cRepository
            .optPasswordResetIdentity("anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("lower-case reset identity was not resolved"))?;
        anyhow::ensure!(stLowerReset.iId == 10);
        anyhow::ensure!(stLowerReset.sNick == "anonymous");
        anyhow::ensure!(stLowerReset.optEmail.as_deref() == Some("lower@example.test"));
        anyhow::ensure!(stLowerReset.dtReset == Utc.with_ymd_and_hms(2026, 2, 3, 4, 5, 6).unwrap());
        anyhow::ensure!(!stLowerReset.bBlocked);
        anyhow::ensure!(!stLowerReset.bActivated);
        anyhow::ensure!(!stLowerReset.bAdministrator);
        anyhow::ensure!(!stLowerReset.bAnonymous);

        let stUpperReset = cRepository
            .optPasswordResetIdentity("Anonymous")
            .await?
            .ok_or_else(|| anyhow::anyhow!("upper-case reset identity was not resolved"))?;
        anyhow::ensure!(stUpperReset.iId == 20);
        anyhow::ensure!(stUpperReset.sNick == "Anonymous");
        anyhow::ensure!(stUpperReset.optEmail.as_deref() == Some("upper@example.test"));
        anyhow::ensure!(
            stUpperReset.dtReset == Utc.with_ymd_and_hms(2026, 7, 8, 9, 10, 11).unwrap()
        );
        anyhow::ensure!(stUpperReset.bBlocked);
        anyhow::ensure!(stUpperReset.bActivated);
        anyhow::ensure!(stUpperReset.bAdministrator);
        anyhow::ensure!(stUpperReset.bAnonymous);
        anyhow::ensure!(
            cRepository
                .optPasswordResetIdentity("ANONYMOUS")
                .await?
                .is_none()
        );

        let stBlockedNull = cRepository
            .optPasswordResetIdentity("blocked-null")
            .await?
            .ok_or_else(|| anyhow::anyhow!("blocked nullable-email identity was not resolved"))?;
        anyhow::ensure!(stBlockedNull.optEmail.is_none());
        anyhow::ensure!(stBlockedNull.bBlocked);

        let stEligibleNull = cRepository
            .optPasswordResetIdentity("eligible-null")
            .await?
            .ok_or_else(|| anyhow::anyhow!("eligible nullable-email identity was not resolved"))?;
        anyhow::ensure!(stEligibleNull.optEmail.is_none());
        anyhow::ensure!(!stEligibleNull.bBlocked);
        anyhow::ensure!(stEligibleNull.bActivated);
        anyhow::ensure!(!stEligibleNull.bAdministrator);
        anyhow::ensure!(!stEligibleNull.bAnonymous);

        anyhow::ensure!(
            cRepository
                .optProfileSettings(stLower.iId)
                .await?
                .as_deref()
                == Some("lower-private-settings")
        );
        anyhow::ensure!(
            cRepository
                .optProfileSettings(stUpper.iId)
                .await?
                .as_deref()
                == Some("upper-private-settings")
        );
        anyhow::ensure!(cRepository.vecEventTypes(stLower.iId).await? == vec!["LowerPrivateReply"]);
        anyhow::ensure!(cRepository.vecEventTypes(stUpper.iId).await? == vec!["UpperPrivateReply"]);
        Ok(())
    }

    #[test]
    fn identity_database_guard_rejects_live_and_mismatched_names() {
        vValidateDisposableIdentityDatabase(
            "lorsource_identity_test_20260816",
            "lorsource_identity_test_20260816",
        )
        .expect("matching disposable identity database");

        for (sCurrent, sExpected) in [
            ("lor", "lor"),
            ("postgres", "postgres"),
            ("template0", "template0"),
            ("template1", "template1"),
            ("live", "live"),
            (
                "lorsource_identity_test_live",
                "lorsource_identity_test_live",
            ),
            (
                "lorsource_identity_test_prod",
                "lorsource_identity_test_prod",
            ),
            ("lorsource_identity_test_one", "lorsource_identity_test_two"),
            ("unrelated_test_database", "unrelated_test_database"),
        ] {
            assert!(
                vValidateDisposableIdentityDatabase(sCurrent, sExpected).is_err(),
                "unsafe database pair was accepted: {sCurrent:?}/{sExpected:?}"
            );
        }
    }

    #[tokio::test]
    #[ignore = "requires a separately created lorsource_identity_test_* throwaway database"]
    async fn case_colliding_identities_never_mix_private_security_rows() {
        assert_eq!(
            std::env::var("LOR_USER_IDENTITY_DB_INTEGRATION_CONFIRM").as_deref(),
            Ok("isolated-schema"),
            "set LOR_USER_IDENTITY_DB_INTEGRATION_CONFIRM=isolated-schema"
        );
        let sDatabaseUrl = std::env::var("LOR_USER_IDENTITY_DB_INTEGRATION_DATABASE_URL").expect(
            "set LOR_USER_IDENTITY_DB_INTEGRATION_DATABASE_URL to the selected PostgreSQL database",
        );
        let sExpectedDatabase =
            std::env::var("LOR_USER_IDENTITY_DB_INTEGRATION_EXPECT_DATABASE").expect(
                "set LOR_USER_IDENTITY_DB_INTEGRATION_EXPECT_DATABASE to the disposable database name",
            );
        let oAdminPool = PgPoolOptions::new()
            .max_connections(1)
            .connect(&sDatabaseUrl)
            .await
            .expect("disposable PostgreSQL database must be reachable");
        let sCurrentDatabase: String = sqlx::query_scalar("SELECT current_database()::text")
            .fetch_one(&oAdminPool)
            .await
            .expect("read current disposable database name");
        vValidateDisposableIdentityDatabase(&sCurrentDatabase, &sExpectedDatabase)
            .expect("identity test requires a named throwaway database, never the live database");

        let sSchema = format!("user_identity_{}", uuid::Uuid::new_v4().simple());
        vExecute(&oAdminPool, &format!("CREATE SCHEMA {sSchema}"))
            .await
            .expect("temporary UUID schema must be creatable");

        let stResult = async {
            let sConnectionSchema = sSchema.clone();
            let oPool = PgPoolOptions::new()
                .max_connections(2)
                .after_connect(move |oConnection, _stMetadata| {
                    let sConnectionSchema = sConnectionSchema.clone();
                    Box::pin(async move {
                        sqlx::query("SELECT set_config('search_path',$1,false)")
                            .bind(sConnectionSchema)
                            .execute(&mut *oConnection)
                            .await?;
                        Ok(())
                    })
                })
                .connect(&sDatabaseUrl)
                .await?;

            let stContractResult = async {
                let sCurrentSchema: String = sqlx::query_scalar("SELECT current_schema()::text")
                    .fetch_one(&oPool)
                    .await?;
                anyhow::ensure!(
                    sCurrentSchema == sSchema,
                    "fixture pool escaped UUID schema: {sCurrentSchema:?}"
                );
                vCreateIdentityFixture(&oPool).await?;
                vProveExactIdentityContract(&oPool).await?;
                vProvePasswordResetRequestOrdering(&oPool).await
            }
            .await;

            oPool.close().await;
            stContractResult
        }
        .await;

        // Cleanup uses a separate admin connection and always runs after the
        // UUID schema has been created, including setup/assertion failures.
        let stDropResult = vExecute(&oAdminPool, &format!("DROP SCHEMA {sSchema} CASCADE")).await;
        oAdminPool.close().await;
        stDropResult.expect("temporary UUID schema cleanup must succeed");
        stResult.expect("exact identity database contract");
    }
}
